### ISSUE TITLE
Update the core repo with the latest spec changes

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydra-python-core#15]
We need to have a detailed analysis about what changes have been made to the spec in the last two years and how do we include them here. We might need a report on current attributes of the spec and what core is missing.

As far as I can see, now that we have separated the repos, all changes to the spec can be done here without having any changes in `hydrus` itself. We expose interfaces for `hydrus` to use core to understand the API, but all spec related changes will be made here from now on.

**Comment by gustavodemorais** [comment]
### Hydrus related 
-----
#### Templated Links (IRI Template)
Related: https://github.com/HTTP-APIs/hydrus/issues/302 
Hydra References:
- https://www.hydra-cg.com/spec/latest/core/#templated-links

#### Description of HTTP Status Codes and Errors
Related: https://github.com/HTTP-APIs/hydra-python-core/issues/18
Hydra References:
- https://www.hydra-cg.com/spec/latest/core/#description-of-http-status-codes-and-errors

#### Client initiated pagination
Related: https://github.com/HTTP-APIs/hydrus/issues/397
Hydra References:

- https://www.hydra-cg.com/spec/latest/core/#client-initiated-pagination
- https://github.com/HydraCG/Specifications/pull/184

### Agent related
------
#### Manages Block
Related: 
Hydra References: 
- https://www.hydra-cg.com/spec/latest/core/#manages-block

#### Returns header and Expects header
Related: 
Hydra References:
- https://github.com/HydraCG/Specifications/pull/185

**Comment by gustavodemorais** [comment]
Will be updating with more links and references from their repository.

Feel free to directly update my comment or write below any other important resource.

**Comment by gustavodemorais** [comment]
#### memberTemplate
Related:
Hydra References:
- https://github.com/HydraCG/Specifications/pull/158
- https://github.com/HydraCG/Specifications/pull/154

This is related to setting the resource target id with IRI, there's an open PR that wasn't yet merged because they decided to hold on for some decisions. It's an important basic feature so I'll leave here as a comment to be checked again in the future.

**Comment by xadahiya** [comment]
@vddesai1871 @Guttz We need to keep this library in sync with the developments going on in hydrus. It should be able to generate Hydra vocabs compatible with the changes being done in hydrus. Also, it should be able to parse and extract information from new hydra vocabs as well. For e.g it should be able to extract IRI template information from a hydra vocab etc.

**Comment by vddesai1871** [comment]
>We need to keep this library in sync with the developments going on in hydrus.

Yes definitely, so far while adding any new feature I have added spec related part of that feature here before updating hydrus as hydrus directly utilizes them.

Now as I am starting work on this issue (updating core and hydrus with latest changes at Hydra), following the same approach I'll create a first PR here and then later update hydrus to accommodate these changes.
