### ISSUE TITLE
SyntaxError: Status must have

### ISSUE THREAD

**Issue by gustavodemorais** [HTTP-APIs/hydra-python-core#27]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Commit https://github.com/HTTP-APIs/hydra-python-core/commit/7cc6db828610f32cce6bd660073573e09c40a8f6 for some reason broke the current doc_maker.create_doc(apidoc) from the Agent. I see that the tests here are running fine so I don't know exactly why, the full log as below. 
![image](https://user-images.githubusercontent.com/11739405/60091271-7a7b9300-9744-11e9-8f45-5c30ceba9a01.png)

I just had to check out before that issue and things works as always, I can help investigate the issue

### Steps to reproduce:

Run default hydrus and try to start the default agent(not necessarily my branch, the current stable one happens the same)

**Comment by vddesai1871** [comment]
As the error says the provided ApiDoc does not contain "title" field in Status object included in possibleStatus. With which ApiDoc are you using hydrus? Does it contain any possibleStatus without title and description field?

**Comment by Guttz** [comment]
That's right, it's the default apidoc that loads at hydrus, the drone one. I just checked and we don't have it in this repo. The possibleStatuses do not have title, 

                    "possibleStatus": [
                        {
                            "description": "singleClass returned",
                            "statusCode": 200
                            "@context": "http://www.w3.org/ns/hydra/context.jsonld",
                            "@type": "Status",
                            "description": "singleClass returned.",
                            "statusCode": 200,
                            "title": ""
                        }
I'll take care of updating it/testing over there and then I ask you if I have a question about it

**Comment by gustavodemorais** [comment]
That's right, it's the default apidoc that loads at hydrus, the drone one. I just checked and we don't have it in this repo. The possibleStatuses are as the old ones that were here, only description and statusCode. We should update all of them as you did with https://github.com/HTTP-APIs/hydra-python-core/blob/master/samples/doc_writer_sample_output.py, right?


```
"possibleStatus": [
    {
        "description": "singleClass returned",
        "statusCode": 200
        "@context": "http://www.w3.org/ns/hydra/context.jsonld",
        "@type": "Status",
        "description": "singleClass returned.",
        "statusCode": 200,
        "title": ""
    }
```

**Comment by vddesai1871** [comment]
Yeah. I remember it well as it's a very frustrating task ;) If I remember correctly I had already made necessary changes. Try using the develop branch (hydrus) instead.
(And from where you posted this code snippet? it's quite scary for me as it has duplicate values :))

**Comment by gustavodemorais** [comment]
Okay, so it's as you've said, it's just a problem of the repo's being in different versions. Hydra python core already has possibleStatuses implementation on master and hydrus still has it on develop.

https://github.com/HTTP-APIs/hydrus/blob/c0e501fea21c114fa8133d287fcbdda52edfefe6/hydrus/samples/hydra_doc_sample.py
