### ISSUE TITLE
How to work with Base.metadata within hydraspec

### ISSUE THREAD

**Issue by de-sh** [HTTP-APIs/hydra-python-core#3]
Hydraspec files as they are written with the flask structure in mind have this line in common`from hydrus.metadata.subsystem_parsed_classes import parsed_classes`. @xadahiya How is it that we have to work with porting this to a new repo?

**Comment by shravandoda** [comment]
I guess you're talking about the parser.py file in hydraspec/legacy, right?
If you take a look at the original hydrus repo, the above module doesn't exist in either of the branches. That's why I skipped them. I assumed since it's legacy, the current version doesn't use them.

**Comment by de-sh** [comment]
No, I mean to be talking about the doc_writer.py and various other files with this exact line within them...

**Comment by de-sh** [comment]
Ok, seems about right, the issue is only within the legacy directory...
