### ISSUE TITLE
Support Old Hydra APIs

### ISSUE THREAD

**Issue by priyanshunayan** [HTTP-APIs/hydra-python-core#36]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Right now, a strict checking is imposed on whether some properties are specified or not and later on properties like `title` and `description` are used to generate hydra-doc. But older versions of docs may or may not contain these properties. We should also be able to generate hydra-doc for these docs as well in order to support older versions.
### Expected Behaviour:

All old and new Hydra based web APIs will be supported. 
@Guttz @xadahiya @Mec-iS @vddesai1871

**Comment by b-thebest** [comment]
Hello sir, can I take up this issue?

**Comment by Mec-iS** [comment]
as Hydra is a under-construction standard and it has not yet been publish version 1.0, back-compatibility cannot be guaranteed.
