### ISSUE TITLE
Generalising the agent so that it works with any hydra enabled API.

### ISSUE THREAD

**Issue by sudipt1999** [HTTP-APIs/hydra-python-core#37]
Currently the agent is strongly tied up with the hydrus, since it is part of the GSoC project I am intrested in I wanted to discuss about it! 
Since it will involve making changes in this repo so I have opened a issue to discuss about it!
@vddesai1871  @Mec-iS

**Comment by xadahiya** [comment]
The agent should work with any hydra API except for the sync mechanism part. Am I missing something @Guttz ?

**Comment by sudipt1999** [comment]
So, if it not a hydrus server then it would not use the graph but will handle the request as per the REST API ! am I right @xadahiya @Guttz

**Comment by chrizandr** [comment]
Not relevant to this repo.
