### ISSUE TITLE
Setup Travis CI for core

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/hydra-python-core#55]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Expected Behaviour:

Setup CI to automatically run tests with Travis

**Comment by de-sh** [comment]
Hey, I remember adding the same here: https://github.com/HTTP-APIs/hydra-python-core/blob/master/.travis.yml

I'd like to help out with this issue in that case!

How about adding a static analysis tool like [DeepSource](https://deepsource.io) to the mix?

**Comment by chrizandr** [comment]
Sounds like a good idea. But I don't think core really need a static analyser at this stage. Maybe open an issue in hydrus?

**Comment by de-sh** [comment]
Awesome, will do!
