### ISSUE TITLE
missing 1 required positional argument: 'doc_name' when using parse(doc)

### ISSUE THREAD

**Issue by roufiq** [HTTP-APIs/hydra-python-core#56]
### I'm submitting a 
- [v] bug report.
- [ ] feature request.

### Current Behaviour:

TypeError: __init__() missing 1 required positional argument: 'doc_name' when using parse(doc)
related with class class HydraDoc:

### Expected Behaviour:

get hydra doc, 

### Do you want to work on this issue?
no

**Comment by Mec-iS** [comment]
please provide steps to reproduce

**Comment by yogi2103** [comment]
I want to work upon this issue and also new in the community please help me with this

**Comment by Mec-iS** [comment]
duplicate #64
