### ISSUE TITLE
Add missing items in the context of response

### ISSUE THREAD

**Issue by priyanshunayan** [HTTP-APIs/hydra-python-core#57]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Some keywords that we are using in the response are not defined in the context. For eg: At the entrypoint(`/serverapi`) of the API we are using `collections` keyword in the response but `collections` is not defined in the context of the entrypoint response. 

### Expected Behaviour:

`collections` should be defined in the context of the entrypoint response.
### Steps to reproduce:

* Start the hydrus server using default arguments.
* Navigate to  "http://localhost:8080/serverapi"
* check the context and response body
### Do you want to work on this issue?

no

**Comment by Mec-iS** [comment]
duplicate #64
