### ISSUE TITLE
Port tests from hydrus

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydra-python-core#6]
Port and update `test_doc_writer.py` from hydrus directory. Moving should be done in a way so that the history is preserved. This might help 
- https://stackoverflow.com/questions/2982055/detach-many-subdirectories-into-a-new-separate-git-repository/2989613#2989613
- https://stackoverflow.com/questions/1365541/how-to-move-files-from-one-git-repo-to-another-not-a-clone-preserving-history

**Comment by Mec-iS** [comment]
see #12

**Comment by xadahiya** [comment]
Remaining in #8
