### ISSUE TITLE
Wrong import in documentation

### ISSUE THREAD

**Issue by king-11** [HTTP-APIs/hydra-python-core#67]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

Documentation has a wrong import in index.rst

### Steps to reproduce:

HydraClass Documentation wrong import

### Do you want to work on this issue?

yes

**Comment by priyanshunayan** [comment]
@king-11 There is also one more mistake in the docs -  In the last few code blocks `api_doc` suddenly changes to `apidoc`. Can you address that too?

**Comment by king-11** [comment]
okay I will look for it add to the pr @priyanshunayan

**Comment by priyanshunayan** [comment]
fixed by #68
