### ISSUE TITLE
Adding "ExportHydradoc" method to doc_writer class

### ISSUE THREAD

**Issue by Purvanshsingh** [HTTP-APIs/hydra-python-core#69]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Currently, we have to explicitly write the code for Saving the HydraDoc Object to a file, for later use.

### Expected Behaviour:

We can have a method inside the doc_writer class named ExportHydradoc() which will save the HydraDoc object to the api_doc_output.py file.

### Do you want to work on this issue?

yes

**Comment by chrizandr** [comment]
There is already a `generate` function to export doc into a python dictionary. It's not a good idea to save docs as python files. The correct way would be to serialize the dictionary into json and save. Which would then be loaded into a python dictionary elsewhere. This requires no additional functions in core to do.

**Comment by Purvanshsingh** [comment]
Yes, got your point but where can we add the method to store doc into JSON,
Because for the `doc_maker` we need to store and load it.

**Comment by chrizandr** [comment]
That's not within the scope of the core library. It's upto the user to decide how to serialize the dictionary. They may use json, yaml, pickle anything. We provide a python dictionary.

**Comment by Purvanshsingh** [comment]
Okay.
Closing the Issue.
