### ISSUE TITLE
supportedProperty for HydraCollection should be writeable

### ISSUE THREAD

**Issue by farazkhanfk7** [HTTP-APIs/hydra-python-core#70]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

In doc_writer.py/HydraCollection's supportedProperty, the `writeable` parameter is set to `False` by default. (Line-280)
https://github.com/HTTP-APIs/hydra-python-core/blob/3795cb0bd8eeb0f310febf17090ca3bdb1b1d135/hydra_python_core/doc_writer.py#L261-L282
Because of this a POST/DELETE request cannot be made to a Collection because even if a Collection has POST method in it's supported operation, hydrus still checks that it should have only writeable properties. As a result a 405 (Method Not Allowed) status code is returned.
### Expected Behaviour:
 `writeable` should be set to True. We could've also left this decision upto API developer by adding `writeable` as a parameter in HydraCollection's constructor but it'll require us to update doc_maker, sample docs and files throughout these repositories. 
Setting `writeable` to True by default seems more like a quick fix for now.

### Steps to reproduce:

Run server with hydrus and make a POST request to a Collection endpoint. 
### Do you want to work on this issue?

**Yes**

**Comment by Megh05** [comment]
@farazkhanfk7 I am interested to work on this issue. Thank You!
