### ISSUE TITLE
Change hydra core fetching in context.

### ISSUE THREAD

**Issue by Purvanshsingh** [HTTP-APIs/hydra-python-core#74]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

hydra core is being fetched from https://www.markus-lanthaler.com/hydra/core

### Expected Behaviour:

It should be fetched from the hydraCG core.jsonld

### Do you want to work on this issue?

yes

**Comment by Mec-iS** [comment]
The alternative is https://www.w3.org/ns/hydra/core

**Comment by Purvanshsingh** [comment]
Do we need to update it? 
I believe Github version will be more stable.

**Comment by Mec-iS** [comment]
How can it be more stable if it incorporates the latest changes every time they are merged?
Please check if the two versions are the same or really close to each other first, if affermative we should prefer the W3C version. I don't know how the publishing mechanism works but the W3C version should be deployed soon after the Github one.

**Comment by Purvanshsingh** [comment]
Sure, will check.
If found similar will create the updated PR.
