### ISSUE TITLE
Fix failing tests in hydra-python-core 

### ISSUE THREAD

**Issue by farazkhanfk7** [HTTP-APIs/hydra-python-core#77]
### I'm submitting a 
- [x] bug report.
- [x] feature request.

### Current Behaviour:

Presently, most of the tests in hydra_python_core are failing. Also, only three tests are present for doc_writer and only for testing the context. Tests need to be fixed to ensure that all code meets quality standards and all components are working as they should.

### Expected Behaviour:

The tests for both doc_writer and doc_maker should pass. The repo needs to be fixed as per pep8 compliance. 

[ Future Improvements ]  Currently, only three tests are present for doc_writer and only for testing the context. More tests should be added in hydra_python_core for different components of  doc_writer like HydraClass, HydraCollection, HydraEntryPoint and many others.

We can also setup a CI with Travis to automatically run tests to avoid this in future. Ref : [see issue](https://github.com/HTTP-APIs/hydra-python-core/issues/55)

### Steps to reproduce:

* `python -m unittest discover`

### Do you want to work on this issue?

**Yes, I am working on it.**

**Comment by Mec-iS** [comment]
I think this is fixed? Please close
