### ISSUE TITLE
[DISCUSSION] Context class in doc_writer.py

### ISSUE THREAD

**Issue by Purvanshsingh** [HTTP-APIs/hydra-python-core#78]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

`class Context` in doc_writer.py is creating context in this format : 

![Screenshot from 2021-05-09 18-10-48](https://user-images.githubusercontent.com/49719371/117572770-0822ba80-b0f2-11eb-9bcd-542f875d034c.png)

And we are expecting it in this format:

![Screenshot from 2021-05-09 18-11-07](https://user-images.githubusercontent.com/49719371/117572783-183a9a00-b0f2-11eb-98e1-f87911d15232.png)

Probably that's why the tests in doc_writer.py are failing

![Screenshot from 2021-05-09 18-13-50](https://user-images.githubusercontent.com/49719371/117572830-5a63db80-b0f2-11eb-8d4d-70f1da31a10b.png)

I have a concern should we add the base address as well in the context for classes, collection & properties?
`"vocab" : base_adderss`

### Do you want to work on this issue?

yes, If it is required to add.

**Comment by farazkhanfk7** [comment]
The format of context was changed in commits by previous contributors and there hasn't been any problem so far. The only problem is failing test cases. I don't think reverting back the changes in doc_writer just to fix the test is a good idea. **We should rather update the tests according to the newly made changes**. The _Context_ class here is used to generate context for HydraDoc and HydraEntrypoint class. Test cases in core repo should be updated. Also we might consider it's expansion or migration to pytest in future. 
[ See Issue ](https://github.com/HTTP-APIs/hydra-python-core/issues/77)

**Comment by Purvanshsingh** [comment]
@farazkhanfk7 Yes, changing context is not a good idea for falling tests, I just highlighted the reason for failing. 
But I just wanna know why we are not including the base address as `vocab: base_address`
Because as expected 
`Class_.title : Class_.id_`  will be 
"Pet" : "vocab:Pet"
In this case I think adding vocab should be required.

**Comment by farazkhanfk7** [comment]
Yes, even I was thought the same at first when I was working to fix the test cases. But this format works totally fine. These changes were made in [this PR](https://github.com/HTTP-APIs/hydra-python-core/pull/45) where the format of these URIs were changed.

**Comment by Purvanshsingh** [comment]
> @farazkhanfk7 Yes, changing context is not a good idea for falling tests, I just highlighted the reason for failing.
> But I just wanna know why we are not including the base address as `vocab: base_address`
> Because as expected
> `Class_.title : Class_.id_` will be
> "Pet" : "vocab:Pet"
> In this case I think adding vocab should be required.

@priyanshunayan Can you please help us in understanding this?

**Comment by priyanshunayan** [comment]
Hi @Purvanshsingh 

> But I just wanna know why we are not including the base address as vocab: base_address

We had taken a call to use expanded `@id` always in order to support as many API Documentations as we could. Different APIDoc authors might have different preferences for eg: why `vocab: base_address` and why not `vocabulary: base_address`. They might even use as `apidoc: base_address` and in those cases, this library will fail to parse those docs. That is why we removed the hard dependency on the vocab keyword and used the expansion algorithm of JSON-LD before parsing the APIDoc and kept the `@id` expanded. That being said you can always use `vocab: base_address` in your APIDoc and core/hydrus/agent should work just fine. 

Does this answer your question?

**Comment by Purvanshsingh** [comment]
@priyanshunayan, got your point It makes hydrus more generic to everyone. 

Thanks for your help.
