### ISSUE TITLE
Write tests for doc_maker.py as well.

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydra-python-core#8]

**Comment by Mec-iS** [comment]
yes. tests should be using the YML files in samples.

**Comment by aribalam** [comment]
The `doc_maker.py` does not have any support for YAML format. How are going to test those?.
Can't we use the normal python dictionary doc to write those tests?

**Comment by shravandoda** [comment]
Can't we just use mocks for testing? `doc_maker` uses `doc_writer`'s methods to create a HydraDoc.
All we'll have to check is whether the functions are being run with proper arguments.

**Comment by gustavodemorais** [comment]
Believe this was implemented at https://github.com/HTTP-APIs/hydra-python-core/pull/14 and https://github.com/HTTP-APIs/hydra-python-core/pull/16 and shall be closed.
